[tool.poetry]
name = "stacklet.client.sinistral"
version = "0.1.0"
description = "Sinistral CLI"
authors = ["Sonny Shi <sonny@stacklet.io>"]
license = "Commercial"
readme = "README.md"

[[tool.poetry.packages]]
include = "stacklet"

[tool.poetry.dependencies]
python = "^3.10"
"stacklet.client.platform" = "^0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "stacklet.client.platform"
url = "https://stacklet-653993915282.d.codeartifact.us-east-1.amazonaws.com/pypi/stacklet.client.platform/simple/"
secondary = true

[tool.poetry.scripts]
sinistral = "stacklet.client.sinistral.cli:cli"
